travis:
  secure:
    BINSTAR_TOKEN: m+R5ssJz6ekA7vkARgClSHomcDAthDuVt1NaLUfnguGxeU6xv6M19G/G9ZJ9tiiWpo6BSE0Y9SziGZkcP+6MHGYk8Wu4ZnPXdzHS2p/TlHw8NycxWhY/Ufk6maZXO0Ibo1xLO+KYNsz9ItnEqkeJyoxmYWTZVzJ0J8xdNGdd+qHp5u8/Ft1ZDMCZ/ggrjmT9ZOdIwigh4GZUsWFYjxuSQTYQHpKs9/TJ2zPcrsTmjnqHnoVAGWSfYhOM9p3jXXvadEBay4m3kgNfGsRuc6HDImYDw1HSFw4qmMhltcAE6yRF12jZmKpoUOftk1moVUw8Rq06C/KZy1UUSZtge4TjXXGqffyxQDaYOaCLpn/N27PAkLUVmZIfKO3muvLzlFJUEFUnBswkhLwnwaCfLT1PfQSDbXpX127aQde2cLa+SetMI0l+4a6rIRCSegqCf3bzbAVWthRKEZmHTaOzyAKCWpqJ/R66jqmdE7rimJsr6N+yZ5iqzzpGdEbhswP5SsjMv370AX51HdqQL52roU9RPLQUMvUSwmmIvO7wUd+EUeqLgJOx7w2KGDnzalIZRvM+bQNZKe7ceWQsmV7Uhg368RHrDbGSRQ0+O76DeO6EfjWf1cmaYy/An6FQ3RfURZbEZis++u28XZgd/xy+QDOMwpPGcz8/Q8jgJWcbR3MBIuI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
